# Generated by Django 3.1.7 on 2021-04-10 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_orders_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='status',
            new_name='completed',
        ),
    ]
